export const mockData = [
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
  {
    firstName: 'concept-j71if',
    lastName: 'sticks-hgw30',
    age: 7,
    visits: 73,
    progress: 53,
    status: 'complicated',
  },
];
